<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <IsPackable>false</IsPackable>
    <RunSettingsFilePath>test.runsettings</RunSettingsFilePath>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\KeyBindings\Nickelony.KeyBindings.Wpf\Nickelony.KeyBindings.Wpf.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\TestHelpers\KeyBindingTestFixtures.cs" Link="TestHelpers\KeyBindingTestFixtures.cs" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
